### ISSUE TITLE
reop doesn't work when being deopped from outside a channel

### ISSUE THREAD

**Issue by cybersans** [Seven-7/gnuworld-enhanced#1]
for example, if mod.cservice(X) bot is in channel #A and i were in that channel issuing /opmode #A -o X, it will alert the oper channel:

[12:34:56] -channelservice.server.irc:#X- [X] I've been DEOPped on #A!
[12:34:56] -channelservice.server.irc:#X- [X] *** OPMODE by thisoper MODE #A -o X

but when i issue the /opmode outside a channel #A, nothing happened, X being deopped and there are no alerts issue, and X stay deopped, and funny things, X still can kick/ban users at #A while not being op.

**Comment by Seven-7** [comment]
I hope the last commit is a suitable fix. Let me know if anything.
