### ISSUE TITLE
gnuworld-enhanced website throws nothing but errors

### ISSUE THREAD

**Issue by StoneC0ld** [Seven-7/gnuworld-enhanced#11]
Hi,
I cloned a fresh version of the gnuworld-enhanced website (for the first time).  I followed your instructions in NEW-Website.txt as best I could, given that debian9 could not install a few of the packages.

Website appears to be accessible by apache2.  But, I get nothing but warnings and errors, all of which are in cmaster.inc, which is completely unmodified.
I've pasted the warnings and errors here:  https://pastebin.com/zehUusS8
Page/tab title shows up as "403 Forbidden", even though the errors and warnings suggest that permissions are correct, though I could be wrong.
Any idea what I'm missing?  Any further information needed?

**Comment by Seven-7** [comment]
https://github.com/Seven-7/website-gnuworld-No-Support-from-Seven/blob/master/README

!!!WARNING!!! I DON'T provide any support for install, bugfix, modification, asking me for any kind of question/support will result in automatic ignore !!!

!!!WARNING!!! I DON'T provide any support for install, bugfix, modification, asking me for any kind of question/support will result in automatic ignore !!!

!!!WARNING!!! I DON'T provide any support for install, bugfix, modification, asking me for any kind of question/support will result in automatic ignore !!!
