### ISSUE TITLE
mod.ccontrol able to autochanmode and kill command

### ISSUE THREAD

**Issue by frootv** [Seven-7/gnuworld-enhanced#2]
dear seven. thank you for your effort of rewriting and enhancing the gnuworld.

i have some suggestions:
1. mod.ccontrol which is "uworld bot" monitor the creation of channel. if user create a new channel, mod.ccontrol will automatically assign automatic channel modes, for example +nt to the newly created channel. when user 1st create a new channel, it will appear *\* services.server sets mode: +nt
2. mod.ccontrol have a command to kill. some oper will not be allowed to kill user by a server admin (they cannot kill user), so the oper can issue command to uworld so that the bot can kill the user. the bot already have gline command, so why not it has kill command too.
3. mod.cservice new feature's hostname has list of hostname that will be allowed. maybe preset hostname so that users are not simply make their ridiculous hostname such as: this.is.my.hostname without proper tld :dancer: 

thanks and regards

**Comment by andreida89** [comment]
Hey.
1. In ircd.conf you can already set default channel modes.

2. That's more of a ircd suggestion , nefarious it already includes override kill.

3. If i remember well it's already done. Hostname requires at least a name.tld and you can also have 1 host per user.

Cheers.

**Comment by Seven-7** [comment]
Yes, blackirc is right, and since https://github.com/Seven-7/gnuworld-enhanced/commit/d4b275a19cc2766821de22afbf767c573e3ab427 you can prevent setting restricted/not allowed hostnames.
