### ISSUE TITLE
EXTENDED_ACCOUNTS

### ISSUE THREAD

**Issue by alfieo** [Seven-7/gnuworld-enhanced#3]
every time a user log's in. it keeps on giving the error below.

Protocol Violation from channels.underx.org: ACCOUNT detected invalid subcommand token 'TestUser'. Old syntax maybe? See EXTENDED_ACCOUNTS F:line

Can you help me fix this.

**Comment by speakzzz** [comment]
Because you need to disable EXTENDED_ACCOUNT

Felix Alcantara
Speakz @IRC
201-208-4454
