### ISSUE TITLE
moduleLoader error

### ISSUE THREAD

**Issue by nite87** [Seven-7/gnuworld-enhanced#5]
Hi,

I am getting the below error msg when tryint to run it

Numeric: 51 (Az)
Max Clients: 1023 (AP])
Uplink Name: 127.0.0.1
Uplink Port: 4400
Server Name: channels.hvymetal.org
Server Description: HvyMetal Services
moduleLoader> Error opening module (../lib/libircu.la): ./../lib/libircu.so.0: wrong ELF class: ELFCLASS32
xServer::loadCommandHandler> Failed to load handler for message token AC, from module file: ../lib/libircu.la, with symbol suffix: msg_AC
~moduleLoader> Error closing module: invalid module handle
xServer::loadCommandHandlers> Failed to load handler for message token AC, from module file: ../lib/libircu.la, with symbol suffix: msg_AC
Loaded 0 command handlers

xServer::initializeSystem> Failed to load command handlers

Any help or clue would be appreciated thank you!

**Comment by Seven-7** [comment]
No error appears if you follow the installation guide:
https://github.com/Seven-7/gnuworld-enhanced/blob/master/INSTALL-NEW-gnuworld.txt

The guide is tested on Ubuntu only.
For learning purposes I strongly recommend to always start on a clean-fresh ubuntu installation.
