### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by one9three** [Seven-7/gnuworld-enhanced#8]
![58D1B7D9-3910-41B7-93FC-3366A8E3F82B](https://user-images.githubusercontent.com/66469410/86211392-e9d26100-bba8-11ea-9b15-345909797836.jpeg)
hi sir how can i unlock this strict current ip address

**Comment by Seven-7** [comment]
https://github.com/Seven-7/website-gnuworld-No-Support-from-Seven/blob/master/README
