### ISSUE TITLE
Mod.OpenChanfix will not compile

### ISSUE THREAD

**Issue by StoneC0ld** [Seven-7/gnuworld-enhanced#9]
Gives me a ton of warnings and/or errors, pasted into a pastebin:

https://pastebin.com/ixQSUVMD

I honestly have no idea if this is an issue with my C++ installation on gentoo linux or if this is an issue in the code itself.....  If I need to change my C++ compilers, please let me know.....

**Comment by Seven-7** [comment]
I hope the last commit fixes that for you
https://github.com/Seven-7/gnuworld-enhanced/commit/cacb0900f3fd205d7b07444faa0c03c5c84d4401

**Comment by StoneC0ld** [comment]
Compiles fine now.  Thanks! :)
